
version: '3.1'
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on: 
      - db
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - db
