project_id                      = "pruebas-4034456"
client_region                   = "us-central1"
client_zone                     = "us-central1-a"
artifact_registry_repository_id = "social-app-frontend-repo"
private-network-name            = "test-fe-private-network"
private-ip-address-name         = "test-fe-private-ip-address"