name: IAC with Terraform manually triggered

on: workflow_dispatch

permissions:
  contents: read

jobs:
  backend-terraform:
    name: 'Setup backend resources'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./infra/backend
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.PRODUCTION_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.PRODUCTION_PROJECT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Download Terraform state
      run: gsutil cp gs://${{ vars.PRODUCTION_BACKEND_BUCKET }}/terraform.tfstate terraform.tfstate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=dev.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=dev.tfvars
      
    - name: Upload Terraform state
      run: gsutil cp terraform.tfstate gs://${{ vars.PRODUCTION_BACKEND_BUCKET }}/terraform.tfstate

  frontend-terraform:
    needs: backend-terraform
    name: 'Setup frontend resources'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./infra/frontend
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.PRODUCTION_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.PRODUCTION_PROJECT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Download Terraform state
      run: gsutil cp gs://${{ vars.PRODUCTION_FRONTEND_BUCKET }}/terraform.tfstate terraform.tfstate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=dev.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=dev.tfvars
      
    - name: Upload Terraform state
      run: gsutil cp terraform.tfstate gs://${{ vars.PRODUCTION_FRONTEND_BUCKET }}/terraform.tfstate
